`define INPUTFILENAME "input.hex"
`define OUTPUTFILENAME "output.bmp"

`define IMG_WIDTH 628
`define IMG_HEIGHT 350

//`define INCREASE_BRIGHTNESS_OPERATION
`define DECREASE_BRIGHTNESS_OPERATION
//`define INVERT_OPERATION
//`define THRESHOLD_OPERATION
//`define SOBEL_OPERATION
//`define GAUSSIAN_OPERATION
//`define CANNY_OPERATION
